import Head from "next/head";
//import Image from 'next/image'
import styles from "../styles/Home.module.css";
import {
  NavBar,
  PhotoContainer,
  EmailForm,
  Footer,
} from "./pageComponents/indexComponents.js";
import {
  Image,
  Button,
  Carousel,
  Card,
  Row,
  Col,
  Jumbotron,
  Container,
  Nav,
} from "react-bootstrap";

/**
    <NavBar />
    <PhotoContainer />
    <EmailForm />
    <Footer />
 * @returns 
 */

export default function Home() {
  return (
    <div>
      <Head>
        <title>Wedding Photographer Site</title>
        <meta name="description" content="Generated by create next app" />
        <link
          href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css"
          rel="stylesheet"
          integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3"
          crossorigin="anonymous"
        />
      </Head>
      <NavBar />
      <PhotoContainer />
      <EmailForm />
      <Footer />

      <script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/ScrollMagic.min.js"></script>
      <script src="//cdnjs.cloudflare.com/ajax/libs/ScrollMagic/2.0.7/plugins/debug.addIndicators.min.js"></script>
    </div>
  );
}
